name: Grid CI

on:
  workflow_call:
  
jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check Docker installation
        run: docker --version

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN  }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Install tools
        run: |
          # Fetch the latest version of `pack` from the GitHub API
          LATEST_VERSION=$(curl -s https://api.github.com/repos/buildpacks/pack/releases/latest | jq -r '.tag_name')

          # Download and install the latest version on Ubuntu
          curl -sSL "https://github.com/buildpacks/pack/releases/download/${LATEST_VERSION}/pack-${LATEST_VERSION}-linux.tgz" | sudo tar -C /usr/local/bin/ --no-same-owner -xzv pack

          # Verify installation
          pack --version

      - name: Get short commit hash
        id: get-commit-hash
        run: |
          echo "hash=$(git rev-parse --short=5 HEAD | tr -d '\n')" >> $GITHUB_ENV
      
      - name: Build Docker image
        run: |
          pack build gridcloud-image:tmp \
            --path . \
            --builder paketobuildpacks/builder-jammy-base
        
      - name: Convert repository-name to lowercase
        id: convert-repository-name
        run: |
          echo "lowercase_repo=$(echo  ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Convert image-name to lowercase
        id: convert-image-name
        run: |
          echo "lowercase_image=$(echo ${{ github.event.repository.name }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Tag Docker Image
        run: |
          docker tag gridcloud-image:tmp ghcr.io/${{ env.lowercase_repo }}/${{ env.lowercase_image }}:${{ env.hash }}
          docker tag gridcloud-image:tmp ghcr.io/${{ env.lowercase_repo }}/${{ env.lowercase_image }}:latest

      - name: Push Docker Image
        run: |
          docker push ghcr.io/${{ env.lowercase_repo }}/${{ env.lowercase_image }}:${{ env.hash }}
          docker push ghcr.io/${{ env.lowercase_repo }}/${{ env.lowercase_image }}:latest
